### ISSUE TITLE
Exec REST's command from program

### ISSUE THREAD

**Issue by Fede22dev** [softwaremill/fablo-rest#40]
Hi, i'm trying to exec command of REST from java program, but when i execute the command it return an error.
My doubt is the following one: can i execute REST's command from program?
Below you can find the program and the error.

```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class Main {
    public static void main(String[] args) throws IOException, InterruptedException {
        BufferedReader console = new BufferedReader(new InputStreamReader(System.in));
        while (true) {
            System.out.print("Command: ");
            switch (console.readLine().strip()) {
                case "enroll" -> {
                    System.out.print("[REST peer PORT]: ");
                    String templateEnroll = "curl --request POST --url http://localhost:PORT/user/enroll --header 'Authorization: Bearer' --data '{\"id\": \"admin\", \"secret\": \"adminpw\"}'";
                    commandExec(templateEnroll.replace("PORT", console.readLine().strip()));
                }
            }
        }
    }

    private static void commandExec(String command) throws IOException, InterruptedException {
        Process proc = Runtime.getRuntime().exec(command);

        BufferedReader reader = new BufferedReader(new InputStreamReader(proc.getInputStream()));
        String line;
        while((line = reader.readLine()) != null) {
            System.out.print(line + "\n");
        }

        proc.waitFor();
    }
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token &#39; in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (/usr/src/app/node_modules/body-parser/lib/types/json.js:158:10)<br> &nbsp; &nbsp;at parse (/usr/src/app/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/usr/src/app/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/usr/src/app/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:412:35)<br> &nbsp; &nbsp;at endReadableNT (internal/streams/readable.js:1334:12)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:82:21)</pre>
</body>
</html>
```

**Comment by dzikowski** [comment]
In your case, I believe, you have some issues with escaping of quotes and the JSON that is sent to Fablo REST becomes invalid.

However, using curl this way is kind of unusual. If you want to query REST API from Java, you should use dedicated client. You may find this page useful: https://fivesmallq.github.io/curl-to-java/. It converts CURL commands to Java code.
